/* The following code was generated by JFlex 1.6.1 */

package lexer;
import static lexer.JFlexToken.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>./src/lexer/JFlexLexer.flex</tt>
 */
public class JFlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\33\1\33\1\33\1\33\1\33\22\0\1\33\1\45\6\0"+
    "\1\43\1\44\1\37\1\35\1\46\1\36\1\31\1\40\12\32\1\47"+
    "\1\0\1\41\1\34\1\42\2\0\11\1\1\14\20\1\4\0\1\31"+
    "\1\0\11\1\1\14\20\1\12\0\1\33\32\0\1\33\u0362\0\1\1"+
    "\1\0\1\11\2\0\1\13\1\1\1\1\1\0\1\1\2\0\1\1"+
    "\1\2\1\3\1\4\1\1\1\5\1\6\1\7\1\10\1\12\1\0"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\1\1\1\1\27\1\30\1\1\7\0\1\2\1\3\1\4\1\1"+
    "\1\5\1\6\1\7\1\10\1\12\1\0\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\1\1\1\1\27\1\30"+
    "\1\1\12\0\1\1\1\0\1\11\2\0\1\13\1\1\1\1\1\0"+
    "\1\1\2\0\1\1\u1220\0\1\33\u097f\0\13\33\35\0\1\33\1\33"+
    "\5\0\1\33\57\0\1\33\u0fa0\0\1\33\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\5\2\1\3\1\2\2\3\5\2\1\3"+
    "\1\2\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\2\2"+
    "\1\22\3\2\1\23\12\2\1\24\1\25\1\26\1\27"+
    "\1\30\1\0\1\31\3\2\1\32\2\2\1\33\10\2"+
    "\1\0\1\34\1\2\1\35\1\2\1\36\3\2\1\37"+
    "\6\2\1\4\1\40\10\2\1\41\1\2\1\42\1\43"+
    "\1\44\1\2\1\45\6\2\1\46\1\2\1\47\13\2"+
    "\1\50\1\2\1\51\1\52\1\53\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\120\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230"+
    "\0\u0258\0\50\0\u0280\0\50\0\u02a8\0\50\0\50\0\50"+
    "\0\50\0\u02d0\0\u02f8\0\u0320\0\50\0\50\0\50\0\50"+
    "\0\u0348\0\u0370\0\120\0\u0398\0\u03c0\0\u03e8\0\120\0\u0410"+
    "\0\u0438\0\u0460\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550"+
    "\0\u0578\0\u05a0\0\50\0\50\0\50\0\50\0\u05c8\0\120"+
    "\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8\0\120\0\u06e0"+
    "\0\u0708\0\u0730\0\u0758\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820"+
    "\0\120\0\u0848\0\120\0\u0870\0\120\0\u0898\0\u08c0\0\u08e8"+
    "\0\120\0\u0910\0\u0938\0\u0960\0\u0988\0\u09b0\0\u09d8\0\50"+
    "\0\u0a00\0\u0a28\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18"+
    "\0\u0b40\0\120\0\u0b68\0\120\0\120\0\120\0\u0b90\0\120"+
    "\0\u0bb8\0\u0be0\0\u0c08\0\u0c30\0\u0c58\0\u0c80\0\120\0\u0ca8"+
    "\0\120\0\u0cd0\0\u0cf8\0\u0d20\0\u0d48\0\u0d70\0\u0d98\0\u0dc0"+
    "\0\u0de8\0\u0e10\0\u0e38\0\u0e60\0\120\0\u0e88\0\120\0\120"+
    "\0\120\0\120";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\6\1\3\1\7"+
    "\1\10\1\11\1\12\2\13\1\14\2\3\1\15\1\16"+
    "\1\17\1\20\1\21\4\3\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\51\0\32\3\16\0\14\3\1\41"+
    "\15\3\16\0\22\3\1\42\7\3\16\0\20\3\1\43"+
    "\11\3\16\0\5\3\1\44\24\3\16\0\5\3\1\45"+
    "\24\3\16\0\11\3\1\46\20\3\16\0\7\3\1\47"+
    "\22\3\16\0\22\3\1\50\7\3\16\0\1\3\1\51"+
    "\30\3\16\0\4\3\1\52\7\3\1\53\6\3\1\54"+
    "\6\3\16\0\1\3\1\55\16\3\1\56\1\3\1\57"+
    "\7\3\16\0\20\3\1\60\11\3\16\0\3\3\1\61"+
    "\6\3\1\47\17\3\16\0\31\62\1\23\51\0\1\63"+
    "\47\0\1\64\5\0\1\65\41\0\1\66\51\0\1\67"+
    "\12\0\20\3\1\70\11\3\16\0\20\3\1\71\11\3"+
    "\16\0\24\3\1\72\5\3\16\0\16\3\1\73\13\3"+
    "\16\0\4\3\1\74\25\3\16\0\1\3\1\75\30\3"+
    "\16\0\23\3\1\76\6\3\16\0\11\3\1\77\20\3"+
    "\16\0\20\3\1\100\11\3\16\0\24\3\1\101\5\3"+
    "\16\0\24\3\1\102\5\3\16\0\3\3\1\103\23\3"+
    "\1\104\2\3\16\0\20\3\1\105\11\3\16\0\2\3"+
    "\1\106\27\3\16\0\22\3\1\107\7\3\16\0\32\62"+
    "\47\0\1\110\16\0\12\3\2\111\16\3\16\0\20\3"+
    "\1\112\11\3\16\0\11\3\1\113\20\3\16\0\20\3"+
    "\1\114\11\3\16\0\12\3\2\115\16\3\16\0\20\3"+
    "\1\116\11\3\16\0\15\3\1\117\14\3\16\0\1\3"+
    "\1\120\30\3\16\0\11\3\1\121\20\3\16\0\24\3"+
    "\1\122\5\3\16\0\5\3\1\123\24\3\16\0\16\3"+
    "\1\124\7\3\1\125\3\3\16\0\20\3\1\126\11\3"+
    "\16\0\24\3\1\127\5\3\47\0\1\110\11\0\1\130"+
    "\4\0\17\3\1\131\12\3\16\0\3\3\1\132\26\3"+
    "\16\0\14\3\1\133\15\3\16\0\11\3\1\134\20\3"+
    "\16\0\3\3\1\135\26\3\16\0\20\3\1\136\11\3"+
    "\16\0\24\3\1\137\5\3\16\0\5\3\1\140\24\3"+
    "\16\0\5\3\1\141\24\3\16\0\24\3\1\142\5\3"+
    "\16\0\11\3\1\143\20\3\16\0\11\3\1\144\20\3"+
    "\16\0\11\3\1\145\20\3\16\0\1\3\1\146\30\3"+
    "\16\0\17\3\1\147\12\3\16\0\11\3\1\150\20\3"+
    "\16\0\22\3\1\151\7\3\16\0\20\3\1\152\11\3"+
    "\16\0\17\3\1\153\12\3\16\0\4\3\1\154\25\3"+
    "\16\0\4\3\1\155\10\3\1\156\14\3\16\0\1\3"+
    "\1\157\30\3\16\0\25\3\1\160\4\3\16\0\14\3"+
    "\1\161\15\3\16\0\15\3\1\162\14\3\16\0\25\3"+
    "\1\163\4\3\16\0\5\3\1\164\24\3\16\0\5\3"+
    "\1\165\24\3\16\0\3\3\1\166\26\3\16\0\11\3"+
    "\1\167\20\3\16\0\22\3\1\170\7\3\16\0\23\3"+
    "\1\171\6\3\16\0\3\3\1\172\26\3\16\0\1\3"+
    "\1\173\30\3\16\0\3\3\1\174\26\3\16\0\1\3"+
    "\1\175\30\3\16\0\17\3\1\176\12\3\16\0\20\3"+
    "\1\177\11\3\16\0\12\3\2\200\16\3\16\0\1\3"+
    "\1\201\30\3\16\0\20\3\1\202\11\3\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3760];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\17\1\1\11\1\1\1\11\1\1\4\11"+
    "\3\1\4\11\22\1\4\11\1\0\20\1\1\0\17\1"+
    "\1\11\52\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String leksema;
public int line;
public int column;

public void updateValues(){
leksema = yytext();
line = yyline;
column = yycolumn;
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JFlexLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 286) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public JFlexToken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { updateValues(); return ERROR;
            }
          case 45: break;
          case 2: 
            { updateValues(); return ID;
            }
          case 46: break;
          case 3: 
            { updateValues(); return NASOKA;
            }
          case 47: break;
          case 4: 
            { updateValues(); return BROJ;
            }
          case 48: break;
          case 5: 
            { /*Ignore*/
            }
          case 49: break;
          case 6: 
            { updateValues(); return OP_ASSIGN;
            }
          case 50: break;
          case 7: 
            { updateValues(); return OP_ADD;
            }
          case 51: break;
          case 8: 
            { updateValues(); return OP_MINUS;
            }
          case 52: break;
          case 9: 
            { updateValues(); return OP_MULTIPLY;
            }
          case 53: break;
          case 10: 
            { updateValues(); return OP_DIVIDE;
            }
          case 54: break;
          case 11: 
            { updateValues(); return OP_LESS;
            }
          case 55: break;
          case 12: 
            { updateValues(); return OP_GREATER;
            }
          case 56: break;
          case 13: 
            { updateValues(); return LPAREN;
            }
          case 57: break;
          case 14: 
            { updateValues(); return RPAREN;
            }
          case 58: break;
          case 15: 
            { updateValues(); return EXCLAMATION;
            }
          case 59: break;
          case 16: 
            { updateValues(); return COMMA;
            }
          case 60: break;
          case 17: 
            { updateValues(); return COLON;
            }
          case 61: break;
          case 18: 
            { updateValues(); return KW_DO;
            }
          case 62: break;
          case 19: 
            { updateValues(); return PRAVEC;
            }
          case 63: break;
          case 20: 
            { updateValues(); return ID_ERROR;
            }
          case 64: break;
          case 21: 
            { updateValues(); return OP_EQUAL;
            }
          case 65: break;
          case 22: 
            { updateValues(); return OP_LESSEQUAL;
            }
          case 66: break;
          case 23: 
            { updateValues(); return OP_NOTEQUAL;
            }
          case 67: break;
          case 24: 
            { updateValues(); return OP_GREATEREQUAL;
            }
          case 68: break;
          case 25: 
            { updateValues(); return KW_AKO;
            }
          case 69: break;
          case 26: 
            { updateValues(); return KW_DZID;
            }
          case 70: break;
          case 27: 
            { updateValues(); return KW_ODI;
            }
          case 71: break;
          case 28: 
            { updateValues(); return KW_BROJ;
            }
          case 72: break;
          case 29: 
            { updateValues(); return KW_ZEMI;
            }
          case 73: break;
          case 30: 
            { updateValues(); return KW_KRAJ;
            }
          case 74: break;
          case 31: 
            { updateValues(); return KW_PATI;
            }
          case 75: break;
          case 32: 
            { updateValues(); return KW_ZHETON;
            }
          case 76: break;
          case 33: 
            { updateValues(); return KW_ROBOT;
            }
          case 77: break;
          case 34: 
            { updateValues(); return  KW_OKOLINA_ZHETON;
            }
          case 78: break;
          case 35: 
            { updateValues(); return KW_OKOLINA_DZID;
            }
          case 79: break;
          case 36: 
            { updateValues(); return KW_NASOKA;
            }
          case 80: break;
          case 37: 
            { updateValues(); return KW_OSTAVI;
            }
          case 81: break;
          case 38: 
            { updateValues(); return KW_OKOLINA;
            }
          case 82: break;
          case 39: 
            { updateValues(); return KW_POCHETOK;
            }
          case 83: break;
          case 40: 
            { updateValues(); return KW_PROCEDURA;
            }
          case 84: break;
          case 41: 
            { updateValues(); return KW_LEVO;
            }
          case 85: break;
          case 42: 
            { updateValues(); return KW_POVTORUVAJ;
            }
          case 86: break;
          case 43: 
            { updateValues(); return KW_PROMENLIVA;
            }
          case 87: break;
          case 44: 
            { updateValues(); return KW_DESNO;
            }
          case 88: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
